### PR TITLE
Version with file

### PR DESCRIPTION
**Pull request by ghickman**
This drops setuptools-scm in favour of versioning via a file and dynamically picking that up with setuptools.

Cutting a release has been wrapped in just for ease of local use.

I've used python to generate the version so I could take advantage of compare `date` instances over comparing strings which need leading zeros removed/added in bash.

Here's an example of running `just release` locally: https://github.com/opensafely-core/pipeline/pull/171  (which I'll close once this is merged because we don't actually need it)

### CODE REVIEW

**Review by bloodearnest — COMMENTED** [review]
Ok, so I think this could be simpler, both in design and implementation.

For periodic manual releases of public releases, YYYY.MM.COUNTER is ok. Although I don't like that the COUNTER could be confused with day of month.

However, for our internal purposes it's more complex than needed.  This complexity pushes into the implementation, resulting in 60 line python script. We can just use YYYY.MM.DD, probably.

I was about to sketch an alternate implementation, but then I found this, which seems to do what we need?

https://autocalver.readthedocs.io/en/latest/index.html

Because this is not a public package, we don't care about the format of the version. But I think that version is fine. Because of PEP440 rules, we can typically pin to YYYY.MM.DD and ignore the seconds.

**Comment by ghickman** [comment]
`autocalver` only runs on 3.9+, but we need to support 3.8 for job-runner/opensafely-cli.

I had a look at [`calver`](https://pypi.org/project/calver/) too, but that only sets the version of the built artefact at build time, so not much use to us.

What's your alternative implementation?

**Comment by bloodearnest** [comment]
> What's your alternative implementation?

`date -u +'%Y.%M.%d.%H%m%S'`, basically

```
$date -u +'%Y.%M.%d.%H%m%S'
2023.39.09.090820
```

It has the same structure as autocalver, but rather than daily seconds, it just smushes H+M+S, which is a) still monotonically increasing and b) carries more information, so I think is actually better than autocalver's format.

We can then just pin to a day downstream, and ingnore the seconds part e.g. pipeline==3.39.09. This will mean we can release multiple in 1 day and the latest one should be used, AIUI.

**Comment by ghickman** [comment]
@bloodearnest – that's much nicer!  I've removed the script and updated the justfile what that call instead.

**Review by bloodearnest — APPROVED** [review]

**Pull request merged**
